from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from GUIs.trailUI import Ui_TrailForm
from GUIs.ForgotDetails import Ui_ForgotDetails_assistance


class Ui_Home(object):
    def __init__(self):
        self.setupUi(Home)

    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(738, 573)
        Home.setAutoFillBackground(False)
        Home.setDocumentMode(False)
        Home.setMaximumSize(QtCore.QSize(738, 573))
        Home.setMinimumSize(QtCore.QSize(738, 573))
        self.centralwidget = QtWidgets.QWidget(Home)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(502, 8, 233, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Access_login_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Access_login_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.Access_login_layout.setContentsMargins(0, 0, 0, 0)
        self.Access_login_layout.setObjectName("Access_login_layout")
        self.access_login_lbl = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("URW Palladio L")
        font.setPointSize(23)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.access_login_lbl.setFont(font)
        self.access_login_lbl.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.access_login_lbl.setStyleSheet("")
        self.access_login_lbl.setObjectName("access_login_lbl")
        self.Access_login_layout.addWidget(self.access_login_lbl)
        self.UserName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.UserName.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.UserName.setPlaceholderText("Enter your Email ID here")
        self.UserName.setObjectName("UserName")
        self.Access_login_layout.addWidget(self.UserName)
        self.Passward = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Passward.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.Passward.setObjectName("Passward")
        self.Passward.setPlaceholderText("Enter your Access Key here")
        self.Access_login_layout.addWidget(self.Passward)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 9, 491, 115))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.InstaAuto_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(75)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.InstaAuto_lbl.setFont(font)
        self.InstaAuto_lbl.setStyleSheet("color: rgb(245, 121, 0);")
        self.InstaAuto_lbl.setObjectName("InstaAuto_lbl")
        self.verticalLayout_2.addWidget(self.InstaAuto_lbl)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(320, 200, 401, 271))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.Premium_vertical_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.Premium_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.Premium_vertical_layout.setObjectName("Premium_vertical_layout")
        self.premium_feature1 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.premium_feature1.setStyleSheet("color: rgb(164, 0, 0);")
        self.premium_feature1.setObjectName("premium_feature1")
        self.Premium_vertical_layout.addWidget(self.premium_feature1)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Premium_vertical_layout.addWidget(self.line)
        self.premium_feature2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.premium_feature2.setStyleSheet("color: rgb(164, 0, 0);")
        self.premium_feature2.setObjectName("premium_feature2")
        self.Premium_vertical_layout.addWidget(self.premium_feature2)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Premium_vertical_layout.addWidget(self.line_2)
        self.premium_feature3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.premium_feature3.setStyleSheet("color: rgb(164, 0, 0);")
        self.premium_feature3.setObjectName("premium_feature3")
        self.Premium_vertical_layout.addWidget(self.premium_feature3)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Premium_vertical_layout.addWidget(self.line_3)
        self.premium_feature4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.premium_feature4.setStyleSheet("color: rgb(164, 0, 0);")
        self.premium_feature4.setObjectName("premium_feature4")
        self.Premium_vertical_layout.addWidget(self.premium_feature4)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.Premium_vertical_layout.addWidget(self.line_4)
        self.premium_feature5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.premium_feature5.setStyleSheet("color: rgb(164, 0, 0);")
        self.premium_feature5.setObjectName("premium_feature5")
        self.Premium_vertical_layout.addWidget(self.premium_feature5)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.Premium_vertical_layout.addWidget(self.line_5)
        self.premium_feature6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.premium_feature6.setStyleSheet("color: rgb(164, 0, 0);")
        self.premium_feature6.setObjectName("premium_feature6")
        self.Premium_vertical_layout.addWidget(self.premium_feature6)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.Premium_vertical_layout.addWidget(self.line_6)
        self.Premium_lbl = QtWidgets.QLabel(self.centralwidget)
        self.Premium_lbl.setGeometry(QtCore.QRect(410, 160, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Premium_lbl.setFont(font)
        self.Premium_lbl.setObjectName("Premium_lbl")
        self.Go_premium_push_button = QtWidgets.QPushButton(self.centralwidget)
        self.Go_premium_push_button.setGeometry(QtCore.QRect(460, 480, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Go_premium_push_button.setFont(font)
        self.Go_premium_push_button.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.Go_premium_push_button.setObjectName("Go_premium_push_button")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 200, 301, 271))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.breif_text_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.breif_text_layout.setContentsMargins(0, 0, 0, 0)
        self.breif_text_layout.setObjectName("breif_text_layout")
        self.breif_text = QtWidgets.QTextBrowser(self.verticalLayoutWidget_4)
        self.breif_text.setObjectName("breif_text")
        self.breif_text_layout.addWidget(self.breif_text)
        self.Trail_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Trail_pushbutton.setGeometry(QtCore.QRect(90, 480, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Trail_pushbutton.setFont(font)
        self.Trail_pushbutton.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.Trail_pushbutton.setObjectName("Trail_pushbutton")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(310, 190, 20, 291))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.Login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Login_btn.setGeometry(QtCore.QRect(630, 120, 101, 31))
        self.Login_btn.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.Login_btn.setObjectName("Login_btn")
        self.forgot_details_btn = QtWidgets.QPushButton(self.centralwidget)
        self.forgot_details_btn.setGeometry(QtCore.QRect(510, 120, 111, 31))
        self.forgot_details_btn.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.forgot_details_btn.setObjectName("forgot_details_btn")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(10, 140, 471, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(60, 145, 341, 21))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(190, 160, 118, 3))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.Message_from_machine_lbl = QtWidgets.QLabel(self.centralwidget)
        self.Message_from_machine_lbl.setGeometry(QtCore.QRect(20, 170, 361, 17))
        self.Message_from_machine_lbl.setStyleSheet("font: 8pt \"Ubuntu\";\n"
                                                    "color: rgb(204, 0, 0);")
        self.Message_from_machine_lbl.setObjectName("Message_from_machine_lbl")
        Home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 738, 22))
        self.menubar.setObjectName("menubar")
        self.menuDeveloper = QtWidgets.QMenu(self.menubar)
        self.menuDeveloper.setObjectName("menuDeveloper")
        self.menuNeed_Technical_Support = QtWidgets.QMenu(self.menuDeveloper)
        self.menuNeed_Technical_Support.setObjectName("menuNeed_Technical_Support")
        self.menuFind_Your_Account = QtWidgets.QMenu(self.menubar)
        self.menuFind_Your_Account.setObjectName("menuFind_Your_Account")
        self.menuTerms = QtWidgets.QMenu(self.menubar)
        self.menuTerms.setObjectName("menuTerms")
        self.menuVersion = QtWidgets.QMenu(self.menubar)
        self.menuVersion.setObjectName("menuVersion")
        Home.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Home)
        self.statusbar.setObjectName("statusbar")
        Home.setStatusBar(self.statusbar)
        self.actionCall_Me = QtWidgets.QAction(Home)
        self.actionCall_Me.setObjectName("actionCall_Me")
        self.actionFeedBack = QtWidgets.QAction(Home)
        self.actionFeedBack.setObjectName("actionFeedBack")
        self.actionRequest_a_Call = QtWidgets.QAction(Home)
        self.actionRequest_a_Call.setObjectName("actionRequest_a_Call")
        self.actionRe = QtWidgets.QAction(Home)
        self.actionRe.setObjectName("actionRe")
        self.actionSearch_My_Account = QtWidgets.QAction(Home)
        self.actionSearch_My_Account.setObjectName("actionSearch_My_Account")
        self.actionPrivacy_Policy = QtWidgets.QAction(Home)
        self.actionPrivacy_Policy.setObjectName("actionPrivacy_Policy")
        self.actionService_Terms = QtWidgets.QAction(Home)
        self.actionService_Terms.setObjectName("actionService_Terms")
        self.actionData_Protection_Policy = QtWidgets.QAction(Home)
        self.actionData_Protection_Policy.setObjectName("actionData_Protection_Policy")
        self.actionCurrent_Version = QtWidgets.QAction(Home)
        self.actionCurrent_Version.setObjectName("actionCurrent_Version")
        self.actionUpdate_Request = QtWidgets.QAction(Home)
        self.actionUpdate_Request.setObjectName("actionUpdate_Request")
        self.actionDelete_My_Account = QtWidgets.QAction(Home)
        self.actionDelete_My_Account.setObjectName("actionDelete_My_Account")
        self.menuNeed_Technical_Support.addSeparator()
        self.menuNeed_Technical_Support.addAction(self.actionRequest_a_Call)
        self.menuDeveloper.addAction(self.menuNeed_Technical_Support.menuAction())
        self.menuDeveloper.addAction(self.actionFeedBack)
        self.menuFind_Your_Account.addAction(self.actionRe)
        self.menuFind_Your_Account.addAction(self.actionSearch_My_Account)
        self.menuFind_Your_Account.addAction(self.actionDelete_My_Account)
        self.menuTerms.addAction(self.actionPrivacy_Policy)
        self.menuTerms.addAction(self.actionService_Terms)
        self.menuTerms.addAction(self.actionData_Protection_Policy)
        self.menuVersion.addAction(self.actionCurrent_Version)
        self.menuVersion.addAction(self.actionUpdate_Request)
        self.menubar.addAction(self.menuDeveloper.menuAction())
        self.menubar.addAction(self.menuFind_Your_Account.menuAction())
        self.menubar.addAction(self.menuTerms.menuAction())
        self.menubar.addAction(self.menuVersion.menuAction())

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "InstaAuto"))
        self.access_login_lbl.setText(_translate("Home", "Premium Log In"))
        self.InstaAuto_lbl.setText(_translate("Home", "InstaAuto"))
        self.premium_feature1.setText(_translate("Home", "- Get access to ultimate engagement and focus."))
        self.premium_feature2.setText(_translate("Home", "- Become eligible for intelligent comment engine API"))
        self.premium_feature3.setText(_translate("Home", "- Guaranteed 250+ following in a 500+ generic followers"))
        self.premium_feature4.setText(_translate("Home", "- Get tunned to have an celebrity like following"))
        self.premium_feature5.setText(_translate("Home", "- Support via mail quick response 24x7"))
        self.premium_feature6.setText(_translate("Home", "- Enjoy +10 days of additional use after expiration of pack"))
        self.Premium_lbl.setText(_translate("Home", "Premium Features"))
        self.Go_premium_push_button.setText(_translate("Home", "Go Premium"))
        self.breif_text.setHtml(_translate("Home",
                                           "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                           "p, li { white-space: pre-wrap; }\n"
                                           "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">We dont share your data with anyone for any use</span>. When you register or use our application, we may take certain information that is relevant and you can question why we require any particular information. <span style=\" font-weight:600;\">Once you apply for account deletion and you get an acknowledgement, you complete information gets wiped out of our system</span>.</p>\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Still for your own concern we highly recommend that you change your critical keys like password and other information entered in this interface after the completion of the service. to save yourself from any breach that any malicious program installed in your system can extract.</p>\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Dont change your password and other information while you are in service.</span></p>\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">We recommend you to not use the account while you are using InstaAuto.</span></p>\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">We use our own APIs and servers. So from our side risk of any breach is none. </p>\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Try out our app and services and go premium to have incredible look on Instagram.</p>\n"
                                           "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">- Devendra Kaithal [Developer]</span></p></body></html>"))
        self.Trail_pushbutton.setText(_translate("Home", "Try It for Today"))
        self.Login_btn.setText(_translate("Home", "Log In"))
        self.forgot_details_btn.setText(_translate("Home", "Forgot Details"))
        self.Message_from_machine_lbl.setText(_translate("Home", "InstaAuto Welcomes You."))
        self.menuDeveloper.setTitle(_translate("Home", "Developer"))
        self.menuNeed_Technical_Support.setTitle(_translate("Home", "Need Technical Support"))
        self.menuFind_Your_Account.setTitle(_translate("Home", "Find Your Account"))
        self.menuTerms.setTitle(_translate("Home", "Terms"))
        self.menuVersion.setTitle(_translate("Home", "Version"))
        self.actionCall_Me.setText(_translate("Home", "Call Me"))
        self.actionFeedBack.setText(_translate("Home", "FeedBack"))
        self.actionRequest_a_Call.setText(_translate("Home", "Request a Call"))
        self.actionRe.setText(_translate("Home", "Re - Activate"))
        self.actionSearch_My_Account.setText(_translate("Home", "Search My Account"))
        self.actionPrivacy_Policy.setText(_translate("Home", "Privacy Policy"))
        self.actionService_Terms.setText(_translate("Home", "Service Terms"))
        self.actionData_Protection_Policy.setText(_translate("Home", "Data Protection Policy"))
        self.actionCurrent_Version.setText(_translate("Home", "Current Version"))
        self.actionUpdate_Request.setText(_translate("Home", "Update Request"))
        self.actionDelete_My_Account.setText(_translate("Home", "Delete My Account"))


class Interact(Ui_Home):
    def __init__(self):
        super(Interact, self).__init__()
        self.TrailForm = QtWidgets.QWidget()
        self.ForgotDetails_assistance = QtWidgets.QWidget()

    def account_logger(self):
        if self.UserName.text() == "devendrakaithal" and self.Passward.text() == "123asd":
            print("Logged in")
            self.Message_from_machine_lbl.setText("Successfully connected. Please wait.")
        else:
            print("failed")
            self.Message_from_machine_lbl.setText("Failed to connect. Please try with correct credentials")

    def forgot_details_helper(self):
        print("Forgot details helper in call")
        self.Message_from_machine_lbl.setText("Connecting to the help. Please wait")
        self.ui = Ui_ForgotDetails_assistance()
        self.ui.setupUi(self.ForgotDetails_assistance)
        self.ForgotDetails_assistance.show()


    def trial_starter(self):
        condition = 1
        if condition:
            self.ui = Ui_TrailForm()
            self.ui.setupUi(self.TrailForm)
            self.TrailForm.show()
            print("Trial activated")
            self.Message_from_machine_lbl.setText(
                "Congratulations. Your trial period is started. It is a one time "                                     "facility.")
        else:
            self.Message_from_machine_lbl.setText("Trial has been expired or service has been suspended. Please Go "
                                                  "premium.")

    def premium_signup(self):
        print("Premium signup started.")
        self.Message_from_machine_lbl.setText("Connecting to the server. Please wait")


class MainWindow(Interact):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.Login_btn.clicked.connect(self.account_logger)
        self.forgot_details_btn.clicked.connect(self.forgot_details_helper)
        self.Trail_pushbutton.clicked.connect(self.trial_starter)
        self.Go_premium_push_button.clicked.connect(self.premium_signup)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QMainWindow()
    ui = MainWindow()
    Home.show()
    sys.exit(app.exec_())
